### ISSUE TITLE
example site not responding

### ISSUE THREAD

**Issue by porjo** [aspic/g-wiki#2]
http://mehl.no:8081/ is not responding

**Comment by mehlium** [comment]
Hi, and thanks for notifying me about this. I will start a new instance later today :-)

**Comment by mehlium** [comment]
The example site is up and running again. :-)

**Comment by ghost** [comment]
ping

**Comment by mehlium** [comment]
It's back up, I should add some autostart after upgrades. Thanks for notifying me :+1:
